# This is a basic workflow to help you get started with Actions

name: Submission Validation

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Challenge1_validation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install python libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r ./.github/requirements.txt

      - name: execute Challenge 1 Verification script
        run: python ./.github/Challenge1_Verification.py --submission-file="./Challenge1/submission/Challenge1_submission.csv"

      - name: describe problem
        if: ${{ failure() }}
        run:
          echo "error"
          
  Challenge2_validation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install python libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r ./.github/requirements.txt
      - name: execute Challenge 2 Verification script
        run: python ./.github/Challenge2_Verification.py --submission-file="./Challenge2/submission/Challenge2_submission.csv"

      - name: describe problem
        if: ${{ failure() }}
        run:
          echo "error"

  Challenge3_validation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install python libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r ./.github/requirements.txt
      - name: execute py script
        run:
          python ./.github/Challenge3_Verification.py

